version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:mysql@db:3306/ecommerce_db"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_REGION: "us-east-1"
      S3_BUCKET_NAME: "imagenes-s3-productos"
      S3_FOLDER_NAME: "Imagenes-Productos"

volumes:
  mysql_data:
