version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    ports:
      - "8007:8007"  # Ajusta aquí para usar el puerto 8007
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:password@db:3306/ecommerce_db"

volumes:
  mysql_data:
